config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/new'
  get 'bookmarks/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "lists#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "and list pairing must be unique" }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks
  has_many :reviews
  has_many :movies, through: :bookmarks, dependent: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :comment, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private
  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
    @movies = Movie.all
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @review = Review.new
    @movies = Movie.all
  end

  def create
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save
      redirect_to list_path(@review.list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def set_list
    @list = List.find(params[:list_id])
  end

  def review_params
    params.require(:review).permit(:comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.input :movie_id, collection: Movie.all, label_method: :title, value_method: :id, prompt: "Select a Movie" %>
  <%= f.submit %>
<% end %>

app/views/bookmarks/_movie_card.html.erb
<div class="justify-content-center cards">
  <% @movies.each do |movie| %>
    <div class="card-movie" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= movie.poster_url %>)">
      <%= movie.title %>
    </div>
  <% end %>
</div>

app/views/bookmarks/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to lists_path, class: "navbar-brand" do %>
      <i class="fa-solid fa-film fs-4 ms-3 text-secondary"></i>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Show Lists", lists_path, class: "btn btn-flat me-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create List", new_list_path, class: "btn btn-flat mr-2" %>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

app/views/bookmarks/new.html.erb
<%= render "navbar" %>
<div class="container-fluid mx-0">
  <div class="row mx-0">
    <div class="justify-content-center col">
      <div class="card-form w-100 sticky-top mt-5">
        <img src="https://smoothphotoscanning.com/wp-content/uploads/2020/07/pic-new-2-e1594364405908.jpg" />
        <div class="card-form-infos d-flex justify-content-center">
          <div>
            <h2>New Bookmark</h2>
            <%= render "form", list: @list, bookmark: @bookmark %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-9">
      <h1 class="fw-bold mt-5">Top rated Movies</h1>
      <%= render "movie_card", movies: @movies %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_banner.html.erb
<div class="banner mb-5"">
  <div class="container">
    <h1>Grab some <strong>Popcorn</strong> it's time to watch <strong>MOVIES</strong>!</h1>
    <p>Start creating your watch list to track all of the movies that you are missing out on</p>
    <%= link_to "Create List", new_list_path, class: "btn btn-flat" %>
  </div>
</div>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/_list_grid.html.erb
<div class="cards mx-2">
  <% @lists.each do |list| %>
    <%= link_to list_path(list) do %>
      <div class="card-movie" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path list.photo.key %>)">
        <%= list.name %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/lists/_movie_card.html.erb
<div class="justify-content-center cards">
  <% @movies.each do |movie| %>
    <div class="card-movie" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= movie.poster_url %>)">
      <%= movie.title %>
    </div>
  <% end %>
</div>

app/views/lists/_review.html.erb
<div class="review">
    <div class="review-comment">
      <p><%= review.comment %></p>
    </div>
</div>

app/views/lists/index.html.erb
<%= render "navbar" %>
<%= render "banner" %>
<%= render "list_grid", lists: @lists %>

app/views/lists/new.html.erb
<%= render "navbar" %>
<div class="container-fluid mx-0">
  <div class="row mx-0">
    <div class="justify-content-center col">
      <div class="card-form w-100 sticky-top mt-5">
        <%= image_tag "film.jpg", alt: "film.jpg" %>
        <div class="card-form-infos d-flex justify-content-center">
          <div>
            <h2>New List</h2>
            <%= render "form", list: @list %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-9">
      <h1 class="fw-bold mt-5">Top rated Movies</h1>
      <%= render "movie_card", movies: @movies %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<%= render "navbar" %>
<div class="container-fluid my-3 ms-5 d-flex align-items-center">
  <span class="fw-bold fs-2"><%= @list.name %></span>
  <%= link_to new_list_bookmark_path(@list) do %>
    <i class="fa-solid fa-circle-plus fs-4 ms-3 text-primary"></i>
  <% end %>
</div>
<div class="container-fluid px-5">
  <%= render "movie_grid", list: @list %>
</div>
<div class="container-fluid my-3 ms-5 d-flex align-items-center">
  <span class="fw-bold fs-2">Reviews</span>
  <%= link_to new_list_review_path(@list) do %>
    <i class="fa-solid fa-circle-plus fs-4 ms-3 text-primary"></i>
  <% end %>
</div>
<div class="container-fluid px-5">
  <% @list.reviews.each do |review| %>
    <%= render "review", review: review %>
  <% end %>
</div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@list, @review] do |f| %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/reviews/_movie_grid.html.erb
<div>
  <div class="justify-content-center cards">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card-movie-info">
      <img src="<%= bookmark.movie.poster_url %>" />
        <div class="card-movie-infos">
          <%= link_to bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
            <i class="fa-solid fa-square-minus"></i>
          <% end %>
          <h2><%= bookmark.movie.title %></h2>
          <p><%= bookmark.comment %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to lists_path, class: "navbar-brand" do %>
      <i class="fa-solid fa-film fs-4 ms-3 text-secondary"></i>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Show Lists", lists_path, class: "btn btn-flat me-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create List", new_list_path, class: "btn btn-flat mr-2" %>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<%= render "navbar" %>
<div class="container-fluid mx-0">
  <div class="row mx-0">
    <div class="justify-content-center col">
      <div class="card-form w-100 sticky-top mt-5">
        <img src="https://smoothphotoscanning.com/wp-content/uploads/2020/07/pic-new-2-e1594364405908.jpg" />
        <div class="card-form-infos d-flex justify-content-center">
          <div>
            <h2>Write review</h2>
            <%= render "form", list: @list, reivew: @review %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-9">
      <h1 class="fw-bold mt-5">Listed Movies</h1>
      <%= render "movie_grid", list: @list %>
    </div>
  </div>
</div>